import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        Global Header
        <AuthProvider>{children}</AuthProvider>
        <ToastContainer position="top-right" />
        Global Footer
      </body>
    </html>
  );
}

// Make the following route path
// /practice/users
// -> Display "Users Page" text on the page
// /practice/users/settings
// -> Display "User Setting" text on the page
// /practice/users/settings/privacy
// -> Display "User Privacy Page" text on the page
// /practice/users/data/[id]
// -> Display "User Data Page: {id}" text on the page
// /practice/users/data/[id]/edit
// -> Display "Edit User Data Page: {id}" text on the page
// Make layouts for /practice/users
// to include User Header and User Footer
